import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="max-w-2xl mx-auto mt-2">
        <p className="font-serif bg-pink-200/75 text-4xl tracking-wide decoration-pink-500 decoration-4">
          異常発音
        </p>
        {children}
      </body>
    </html>
  );
}
